### ISSUE TITLE
Costa Rica IBAN length should be 22 instead of 21

### ISSUE THREAD

**Issue by PaddoSwam** [janv8000/IbanValidation#1]
Found a small bug, luckily we never actually ran into a Costa Rican account holder but they wouldn't be able to enter their IBAN if requested by our system.

**Actual:**
`{"CR", 21},`

**Expected:**
CountryCode: CR
Length: 22

**Sources:**
- [The Tico Times](http://www.ticotimes.net/2016/12/15/banks-iban-costa-rica)
- [bank.codes](https://bank.codes/iban/structure/costa-rica/)

**Comment by janv8000** [comment]
Thx for spotting this. I'll look into it when I get home from vacation.

**Comment by PaddoSwam** [comment]
I've got quite a pull request up including this fix, many new country codes and quite some unit test cases to proof them. 😄

**Comment by janv8000** [comment]
Fixed by #2 , thx Tom, updated NuGet coming soon

**Comment by PaddoSwam** [comment]
@janv8000 bump for the nuget package 😄 or should I take a look at that?

**Comment by janv8000** [comment]
Thx for the reminder, NuGet is online at https://www.nuget.org/packages/IbanValidation/1.1.0, could you take a look?
