### ISSUE TITLE
net standard version

### ISSUE THREAD

**Issue by kferstl** [janv8000/IbanValidation#3]
We are migrating to netstandard / netcore, and woul'd love to see this library in the new fancy world again, it helped us a lot. Do you have any plans for that? We could assist migrating it to netstandard 2.0 but someone would need to do the Mvc version. 

Cheers, Kjartan

**Comment by janv8000** [comment]
Hey Kjartan,

Thanks for the interest.

I don’t have a lot of experience yet with .net standard, could you help me out with a pull-request?
Doesn’t have to be polished yet, it’s just to help me get started.

Greetings,

Jan

**Comment by jornj** [comment]
I have a version with netstandard/net45 support. I've made a pull request now. Not so sure I got the web-part right ;-) It's not tested.

Cheers, Jørn

**Comment by jacobduijzer** [comment]
Any change @jornj's PR will be merged? I have a local nuget package from a fork, also netstandard / multitarget but if nothing happens I guess we should release a fork to nuget.

**Comment by janv8000** [comment]
Version 2.0 was just published at https://www.nuget.org/packages/IbanValidation/2.0.0, please check it out
